security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        App\Entity\User:
            algorithm: auto
    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
#        chain_provider:
#            chain:
#                providers: [fos_userbundle]

#        fos_userbundle:
#            id: fos_user.user_provider.username
    firewalls:
#        login:
#            pattern:  ^/api/login
#            provider: chain_provider
#            stateless: true
#            anonymous: true
#            json_login:
#                check_path: /authentication_token
#                success_handler: lexik_jwt_authentication.handler.authentication_success
#                failure_handler: lexik_jwt_authentication.handler.authentication_failure
#                require_previous_session: false
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        api:
            pattern: ^/api/
            stateless: true
            anonymous: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: true
            json_login:
                check_path: /authentication_token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            form_login:
                provider: app_user_provider
                check_path: /login_check
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /home
        refresh:
            pattern:  ^/token/refresh
            stateless: true
            anonymous: true

#            logout:
#                path: /logout
#                target: /login
#        api:
#            pattern:   ^/api/
#            anonymous: true
#            stateless: true
#            provider: chain_provider
#            guard:
#                authenticators:
#                    - lexik_jwt_authentication.jwt_token_authenticator
        rdk_password_reset:
            pattern: ^/password/reset/prm
            anonymous: true
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#        main:
#            anonymous: true
##            pattern: ^/
##            form_login:
##                provider: chain_provider
##                always_use_default_target_path: true
##                csrf_token_generator: security.csrf.token_manager
##                default_target_path: /home
#
#            json_login:
#                check_path: /authentication_token
#                username_path: email
#                password_path: password
#                success_handler: lexik_jwt_authentication.handler.authentication_success
#                failure_handler: lexik_jwt_authentication.handler.authentication_failure
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/resetting-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/resetting/send-mail, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/resetting/reset/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/change-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
#        - { path: /home, roles: ROLE_ADMIN }
