INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (1, 'DAO et affichage en attente validation CNM');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (2, 'PPM en cours d''élaboration');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (3, 'PPM en attente validation CNM');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (4, 'DAO en cours d''élaboration');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (5, 'DAO et affichage en attente validation CNM');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (6, 'AO lancé');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (7, 'Evaluations offres en cours');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (8, 'Attribution - Contractualisation en cours');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (9, 'Signature marché-Visa CF-OS en cours');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (10, 'Visa CF 1er semestre 2020-Travaux en cours');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (11, 'Travaux en cours d''exécution');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (12, 'Mandatement en cours');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (13, 'Livraison en cours');
INSERT INTO public.prm_situation_projet(id, libelle) OVERRIDING SYSTEM VALUE VALUES (14, 'Livraison effectuée ');